apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: soatdb-statefulset
spec:
  serviceName: soatdb-h
  template:
    metadata:
      name: soatdb-statefulset
      labels:
        app: soatdb-statefulset
    spec:
      containers:
        - name: soatdb-statefulset
          image: mysql:5.6
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: soatdb-configmap
  selector:
    matchLabels:
      app: soatdb-statefulset